// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, email string) (Account, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccountByID(ctx context.Context, id uuid.UUID) error
	DeleteTodo(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetTodo(ctx context.Context, id uuid.UUID) (Todo, error)
	GetTodos(ctx context.Context) ([]Todo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	UpdateAccountByID(ctx context.Context, arg UpdateAccountByIDParams) error
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) error
}

var _ Querier = (*Queries)(nil)
